### ISSUE TITLE
Cone crusher generates high mass flow

### ISSUE THREAD

**Issue by gladk** [FlowsheetSimulation/Dyssol-open#49]
Cone crusher generates a high mass flow. See an attached simulation. After the simulation start the output mass flow is about 1200 kg/s, though the input mass flow is 100.
![Screenshot at 2021-11-05 09-14-20](https://user-images.githubusercontent.com/1476497/140479504-ae7d732b-8d48-4035-8003-415c2437bd10.png)
[Abschnitt_2.dflw.tar.gz](https://github.com/FlowsheetSimulation/Dyssol-open/files/7481626/Abschnitt_2.dflw.tar.gz)

[Materials.dmdb.tar.gz](https://github.com/FlowsheetSimulation/Dyssol-open/files/7481627/Materials.dmdb.tar.gz)

**Comment by vasylskorych** [comment]
If this were the case, inlet and outlet of the mill would be different. But now it is:
![image](https://user-images.githubusercontent.com/4201436/140496443-aab28fa3-d96a-4e22-9eca-a9a065b00cf9.png)
What you compare, is inlet with some stream inside the recycle loop. And because of the large holdups inside the recycle, the system has quite large inertia, so it needs time for reaching steady state. 
The only thing one can compare here is the total inlet to the flowsheet and the total output from the flowsheet. And they are the same, if to simulate for a longer time interval:
![image](https://user-images.githubusercontent.com/4201436/140498081-b31d62be-192e-4860-be18-2e834ace7a60.png)
Here is a flowsheet that works for me:
[Abschnitt_2_new_empty.zip](https://github.com/FlowsheetSimulation/Dyssol-open/files/7482442/Abschnitt_2_new_empty.zip)

**Comment by gladk** [comment]
Thank you for explanation!
